alertmanager:
  config:
    route:
      receiver: "aws-webhook"
      group_by: ["alertname", "service"]
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 30m
    receivers:
    - name: "aws-webhook"
      webhook_configs:
      - url: "https://<API_GATEWAY_ID>.execute-api.<REGION>.amazonaws.com/prod/alert"
        send_resolved: true
